module.exports = [
  'global::ensure-department-after-user',
  'global::ensure-work-location-after-user',
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'global::capture-feedback-body',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
